# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExerciseShowCase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExerciseShowCase
  pod 'Alamofire'
  pod 'Kingfisher'
  target 'ExerciseShowCaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
